### ISSUE TITLE
goldener Kavalier Karten können nicht einglöst werden

### ISSUE THREAD

**Issue by Keksgesicht** [Keksgesicht/Brettspiel_Risiko#1]
Botton zum Einlösen der Karten taucht nicht auf.
Die Frage bisher ist noch, ob überhaupt Karten verteilt werden.

**Comment by Keksgesicht** [comment]
zusätzlich zum Würfeln wäre ein Consolen-Output nützlich:
- verteilen 
- einlösen

**Comment by Unknown3141592** [comment]
Das geht jetzt, man muss sich allerdings noch Gedanken machen, wie man dem Spieler verdeutlicht, dass die Karten zwangseingestzt wurden.
Auch, wann der Button sichtbar ist (und vor allen Dingen) wann nicht, muss noch verbessert werden.
